#include <mpfr.h>
#include <flint/arb.h>
#include <flint/arb_poly.h>
#include <flint/arf.h>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <random>
#include <vector>
static constexpr int GEN=4096,REF=2048,MAXT=900,N=5000;
static int terms(double a){double t;if(a<3)t=10+10.5*a-2.14*a*a;else if(a<=10)t=11+5*a;else if(a<=40)t=11+4.54*a+.0485*a*a;else t=-37+6.85*a+.0194*a*a;return std::max(6,(int)ceil(t)+1);}static uint64_t key(double x){union{double d;uint64_t u;}v{x};return(v.u>>63)?~v.u:(v.u|0x8000000000000000ULL);}static uint64_t ud(double a,double b){if(std::isnan(a)||std::isnan(b))return UINT64_MAX;auto x=key(a),y=key(b);return x>y?x-y:y-x;}
struct Data{std::vector<double>A,R;std::vector<arf_struct>C;Data():A(N),R(N),C(MAXT){std::mt19937_64 g1(0x9911223344556677ULL),g2(0x7766554433221199ULL);std::uniform_real_distribution<double>di(1e-12,3.0),doo(3.0,102.0);for(int i=0;i<N/2;i++){double x=di(g1);if(x>=3)x=std::nextafter(3.0,0.0);A[i]=x;}for(int i=N/2;i<N;i++){double x=doo(g2);if(x<=3)x=std::nextafter(3.0,INFINITY);A[i]=x;}double sp[]={2.9,2.99,2.9999,std::nextafter(3.0,0.0),std::nextafter(3.0,INFINITY),3.0001,10,40,50,75,81.764554025359956,100.10072209666959,102};for(size_t i=0;i<sizeof(sp)/sizeof(sp[0]);i++)A[i]=sp[i];arb_poly_t s,z;arb_poly_init(s);arb_poly_init(z);arb_t one,tc,p3,inv,aa,ss,r;arb_init(one);arb_init(tc);arb_init(p3);arb_init(inv);arb_init(aa);arb_init(ss);arb_init(r);arb_one(one);arb_poly_set_coeff_si(s,0,-2);arb_poly_set_coeff_si(s,1,1);fprintf(stderr,"Generating coefficients...\n");arb_poly_zeta_series(z,s,one,0,MAXT+1,GEN);arb_set_ui(p3,9);for(int m=0;m<MAXT;m++){arf_init(C.data()+m);arb_poly_get_coeff_arb(tc,z,m+1);arb_inv(inv,p3,GEN);arb_add(tc,tc,inv,GEN);arf_set_round(C.data()+m,arb_midref(tc),GEN,ARF_RND_NEAR);arb_mul_ui(p3,p3,3,GEN);}for(int i=0;i<N;i++){arb_set_d(aa,A[i]);arb_sub_ui(ss,aa,2,REF);arb_zeta(r,ss,REF);R[i]=arf_get_d(arb_midref(r),ARF_RND_NEAR);}arb_clear(r);arb_clear(ss);arb_clear(aa);arb_clear(inv);arb_clear(p3);arb_clear(tc);arb_clear(one);arb_poly_clear(z);arb_poly_clear(s);}~Data(){for(auto &x:C)arf_clear(&x);}};
static void eval(const Data&d,int bits,int mode,std::vector<double>&Y){Y.resize(N);arf_t a,p,tmp,base,third;arf_init(a);arf_init(p);arf_init(tmp);arf_init(base);arf_init(third);arf_set_ui(third,1);arf_div_ui(third,third,3,bits,ARF_RND_NEAR);for(int i=0;i<N;i++){arf_set_d(a,d.A[i]);int T=terms(d.A[i]);arf_set(p,d.C.data()+T-1);for(int m=T-2;m>=0;m--){if(mode==0){arf_mul(p,p,a,bits,ARF_RND_NEAR);arf_add(p,p,d.C.data()+m,bits,ARF_RND_NEAR);}else arf_fma(p,p,a,d.C.data()+m,bits,ARF_RND_NEAR);}arf_mul(p,p,a,bits,ARF_RND_NEAR);arf_sub_ui(base,a,3,bits,ARF_RND_NEAR);arf_ui_div(base,1,base,bits,ARF_RND_NEAR);arf_add(p,p,base,bits,ARF_RND_NEAR);arf_add(p,p,third,bits,ARF_RND_NEAR);Y[i]=arf_get_d(p,ARF_RND_NEAR);}arf_clear(third);arf_clear(base);arf_clear(tmp);arf_clear(p);arf_clear(a);}
static void report(const char*n,const Data&d,const std::vector<double>&Y){uint64_t mx=0;int gt1=0,gt2=0,w=0;for(int i=0;i<N;i++){auto e=ud(Y[i],d.R[i]);if(e>mx){mx=e;w=i;}gt1+=e>1;gt2+=e>2;}printf("%-16s MAX_ULP=%llu GT1=%d/%d GT2=%d/%d WORST_A=%.17g T=%d\n",n,(unsigned long long)mx,gt1,N,gt2,N,d.A[w],terms(d.A[w]));}
template<class F>static double bench(F&&f){std::vector<double>y;f(y);double best=1e300;for(int r=0;r<3;r++){auto a=std::chrono::steady_clock::now();f(y);auto b=std::chrono::steady_clock::now();best=std::min(best,std::chrono::duration<double,std::nano>(b-a).count()/N);}return best;}
int main(){Data d;std::vector<double>y;eval(d,384,0,y);report("muladd_384",d,y);const int B[]={384,416,448,480,512,576,640,704,768,896,1024};for(int b:B){eval(d,b,1,y);char n[40];snprintf(n,sizeof(n),"fma_%d",b);report(n,d,y);}printf("BENCH_NS_PER_ELEMENT muladd384=%.3f fma384=%.3f fma448=%.3f fma512=%.3f fma640=%.3f fma768=%.3f\n",bench([&](auto&v){eval(d,384,0,v);}),bench([&](auto&v){eval(d,384,1,v);}),bench([&](auto&v){eval(d,448,1,v);}),bench([&](auto&v){eval(d,512,1,v);}),bench([&](auto&v){eval(d,640,1,v);}),bench([&](auto&v){eval(d,768,1,v);}));flint_cleanup();}
