#include <flint/arb.h>
#include <flint/arb_poly.h>
#include <flint/arf.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <random>
#include <vector>
static constexpr int GEN=8192,REF=1024,WB=384,MAXT=900,N=20000;
static int baseT(double a){double t;if(a<3)t=10+10.5*a-2.14*a*a;else if(a<=10)t=11+5*a;else if(a<=40)t=11+4.54*a+.0485*a*a;else t=-37+6.85*a+.0194*a*a;return std::max(6,(int)ceil(t));}static uint64_t key(double x){union{double d;uint64_t u;}v{x};return(v.u>>63)?~v.u:(v.u|0x8000000000000000ULL);}static uint64_t ud(double a,double b){if(std::isnan(a)||std::isnan(b))return UINT64_MAX;auto x=key(a),y=key(b);return x>y?x-y:y-x;}
int main(){std::vector<double>A(N),R(N);std::mt19937_64 g1(0x20A1C0FFEEULL),g2(0x20B2C0FFEEULL);std::uniform_real_distribution<double>di(1e-12,3.0),doo(3.0,102.0);for(int i=0;i<N/2;i++){double x=di(g1);if(x>=3)x=std::nextafter(3.0,0.0);A[i]=x;}for(int i=N/2;i<N;i++){double x=doo(g2);if(x<=3)x=std::nextafter(3.0,INFINITY);A[i]=x;}double sp[]={2.8791775874892278,2.9,2.99,2.9999,std::nextafter(3.0,0.0),std::nextafter(3.0,INFINITY),3.0001,4,10,20,40,50,75,81.764554025359956,100,100.10072209666959,101,102};for(size_t i=0;i<sizeof(sp)/sizeof(sp[0]);i++)A[i]=sp[i];
 arb_poly_t s,z;arb_poly_init(s);arb_poly_init(z);arb_t one,tc,p3,inv,aa,ss,rr;arb_init(one);arb_init(tc);arb_init(p3);arb_init(inv);arb_init(aa);arb_init(ss);arb_init(rr);arb_one(one);arb_poly_set_coeff_si(s,0,-2);arb_poly_set_coeff_si(s,1,1);fprintf(stderr,"Generating coefficients at %d bits...\n",GEN);arb_poly_zeta_series(z,s,one,0,MAXT+1,GEN);std::vector<arf_struct>C(MAXT);arb_set_ui(p3,9);for(int m=0;m<MAXT;m++){arf_init(C.data()+m);arb_poly_get_coeff_arb(tc,z,m+1);arb_inv(inv,p3,GEN);arb_add(tc,tc,inv,GEN);arf_set_round(C.data()+m,arb_midref(tc),WB,ARF_RND_NEAR);arb_mul_ui(p3,p3,3,GEN);}for(int i=0;i<N;i++){arb_set_d(aa,A[i]);arb_sub_ui(ss,aa,2,REF);arb_zeta(rr,ss,REF);R[i]=arf_get_d(arb_midref(rr),ARF_RND_NEAR);}
 for(int guard=0;guard<=3;guard++){for(int mode=0;mode<2;mode++){arf_t a,p,base,third;arf_init(a);arf_init(p);arf_init(base);arf_init(third);arf_set_ui(third,1);arf_div_ui(third,third,3,WB,ARF_RND_NEAR);uint64_t mx=0;int gt1=0,gt2=0,bad=0,w=0;long long tsum=0;for(int i=0;i<N;i++){arf_set_d(a,A[i]);int T=baseT(A[i])+guard;T=std::max(6,T);tsum+=T;arf_set(p,C.data()+T-1);for(int m=T-2;m>=0;m--){if(mode==0)arf_fma(p,p,a,C.data()+m,WB,ARF_RND_NEAR);else{arf_mul(p,p,a,WB,ARF_RND_NEAR);arf_add(p,p,C.data()+m,WB,ARF_RND_NEAR);}}arf_mul(p,p,a,WB,ARF_RND_NEAR);arf_sub_ui(base,a,3,WB,ARF_RND_NEAR);arf_ui_div(base,1,base,WB,ARF_RND_NEAR);arf_add(p,p,base,WB,ARF_RND_NEAR);arf_add(p,p,third,WB,ARF_RND_NEAR);double y=arf_get_d(p,ARF_RND_NEAR);uint64_t e=ud(y,R[i]);if(e==UINT64_MAX){bad++;continue;}if(e>mx){mx=e;w=i;}gt1+=e>1;gt2+=e>2;}printf("GUARD=%d MODE=%s MEAN_T=%.6f MAX_ULP=%llu GT1=%d/%d GT2=%d/%d NONFINITE=%d WORST_A=%.17g T=%d\n",guard,mode==0?"FMA":"MULADD",(double)tsum/N,(unsigned long long)mx,gt1,N,gt2,N,bad,A[w],std::max(6,baseT(A[w])+guard));arf_clear(third);arf_clear(base);arf_clear(p);arf_clear(a);}}
 for(auto&x:C)arf_clear(&x);arb_clear(rr);arb_clear(ss);arb_clear(aa);arb_clear(inv);arb_clear(p3);arb_clear(tc);arb_clear(one);arb_poly_clear(z);arb_poly_clear(s);flint_cleanup();}
